apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airline-demo-prod
  namespace: openshift-gitops
spec:
  destination:
    namespace: airline-demo-prod
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: ocp/overlays/prod
    repoURL: 'git@github.com:philipfoster/airline-dmn-demo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
