apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app: airline-demo
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
  - servicemonitor.yaml
#secretGenerator:
#  - name: dockercfg-secret
#    files:
#      - config.json
images:
  - name: airline-demo
