apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: airline-demo
  name: "airline-demo-metrics"
spec:
  endpoints:
    - interval: 10s
      port: http
      scheme: http
      path: /q/metrics
  selector:
    matchLabels:
      app: airline-demo