kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: monitoring-devs-grant
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: monitoring-devs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: monitoring-edit
